# Generated by Django 3.0.5 on 2021-03-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliceT1app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedoc',
            name='url',
            field=models.CharField(max_length=256),
        ),
    ]
